# -*- coding: utf-8 -*-
"""Problem2_Xue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prPixQse2e1iyHivFA3dl9aKUS6yrF77
"""

from google.colab import files
upload = files.upload ()

#Step 1: Load the data from text file

import pandas as pd
df = pd.read_csv('new_purchases.txt', sep = '\t', header = None)

# assign column names based on the data
df.columns = ['Date', 'Time', 'City', 'Category', 'Transaction Amount', 'Payment Method']

#Filter the data for New York and San Francisco
ny_data = df[df['City'] == 'New York']
sf_data = df[df['City'] == 'San Francisco']

#Calculate the average transaction
ny_avg = ny_data['Transaction Amount'].mean()
sf_avg = sf_data['Transaction Amount'].mean()

#count number of transactions
ny_count = (ny_data).shape[0]
sf_count = (sf_data).shape[0]

#Compare the averages and find city with higher average
if ny_avg > sf_avg:
  higher_city = 'New York'
  lower_city ='San Francisco'
else:
  higher_city = 'San Francisco'
  lower_city = 'New York'

#output results

output = [f'The average transaction amount based on {ny_count} transactions in New York is {ny_avg}.' ,
          f'The average transaction amount based on {sf_count} transactions in San Francisco is {sf_avg}.' ,
          f'{higher_city} has a higher average transaction amount than {lower_city}.']

output_str = '\n'.join(output)

with open('output.txt', 'w') as f:
  f.write(output_str)